version: '3.8'

services:
  # api
  api:
    build:
      context: ./basic_server
      dockerfile: Dockerfile

    expose:
      - 8080

    deploy:
      replicas: 4
    
    restart: always

    environment:
      - PING_LISTEN_PORT=8080

  # Proxy
  proxy:
    image: nginx:latest

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    
    ports:
      - 8081:80

    depends_on: 
      - api
